name: TVerClient
options:
  bundleIdPrefix: dev.nmt3325
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: 5.0
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
targets:
  TVerClient:
    type: application
    platform: iOS
    sources:
      - path: TVerClient
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.nmt3325.TVerClient
        PRODUCT_NAME: TVerClient
        INFOPLIST_KEY_CFBundleDisplayName: TVer Client
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UIBackgroundModes: [audio]
        GENERATE_INFOPLIST_FILE: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    scheme:
      testTargets: [TVerClientTests]
  TVerClientTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TVerClientTests
    dependencies:
      - target: TVerClient
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
